import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "../public/css/globals.css";
import "../public/css/main.css";
import Header from "../components/header";
import Footer from "../components/footer";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "My Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div id="root">
                    <Header/>
                    {children}
                    <Footer />
                </div>
            </body>
        </html>
    );
}
